StopItEF/Models/Link.cs
using System;
using System.Collections.Generic;

namespace StopItEF.Models
{
    public partial class Link
    {
        public Link()
        {
            Comments = new HashSet<Comment>();
            Votes = new HashSet<Vote>();
        }

        public int LinkId { get; set; }
        public int? UserId { get; set; }
        public string Title { get; set; } = null!;
        public string? Description { get; set; }
        public DateOnly? PublicationDate { get; set; }

        public virtual User? User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}

StopItEF/Controllers/LinksController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StopItEF.Models;

namespace StopItEF.Controllers
{
    public class LinksController : Controller
    {
        cloakinglebg_webserverContext _context;
        DateOnly _today;

        public LinksController(cloakinglebg_webserverContext context)
        {
            _context = context;
            _today = DateOnly.FromDateTime(DateTime.Now);
        }


        public ActionResult ViewLink(int linkId)
        {
            Link? linkToView = _context.Links.Where(l => l.LinkId == linkId).FirstOrDefault();
            if (linkToView.UserId != null)
            {
                linkToView.User = _context.Users.Where(u => u.UserId == linkToView.UserId).FirstOrDefault();
            }
            else
            {
                linkToView.User = new User { Pseudo = "[Deleted User]" };
            }
            linkToView.Votes = _context.Votes.Where(v => v.LinkId == linkToView.LinkId).ToList();
            linkToView.Comments = _context.Comments.Where(c => c.LinkId == linkToView.LinkId).OrderByDescending(c => c.PublicationDate).ToList();

            foreach(var comment in linkToView.Comments)
            {
                if (comment.UserId != null)
                {
                    comment.User = _context.Users.Where(u => u.UserId == comment.UserId).FirstOrDefault();
                }
                else
                {
                    comment.User = new User { Pseudo = "[Deleted User]" };
                }
            }

            return View(linkToView);
        }

        public IActionResult ViewOwnLinks(string username)
        {
            User? connected = _context.Users.Where(u => u.Pseudo.Equals(username)).FirstOrDefault();
            List<Link> model = new List<Link>();
            string? success = TempData["Message"] as string;
            if (success != null)
                ViewBag.Success = success;
            if (connected != null)
            {
                model = _context.Links.Where(l => l.UserId == connected.UserId).ToList();
            }
            if(model.Count > 0)
            {
                foreach (Link link in model)
                {
                    link.Comments = _context.Comments.Where(c => c.LinkId == link.LinkId).ToList();
                    link.Votes = _context.Votes.Where(v => v.LinkId == link.LinkId).ToList();
                    if (link.UserId != null)
                    {
                        link.User = _context.Users.Where(u => u.UserId == link.UserId).FirstOrDefault();
                    }
                    else
                    {
                        link.User = new User { Pseudo = "[Deleted User]" };
                    }
                }
                return View(model.OrderByDescending(m => m.Votes.Sum(v => v.Value)).ToList());
            }
            return View();
        }

        public IActionResult DeleteLink(int linkid)
        {
            Link? linkToDelete = _context.Links.Where(l => l.LinkId == linkid).FirstOrDefault();
            if(linkToDelete != null)
            {
                _context.Links.Remove(linkToDelete);
                _context.SaveChanges();
                TempData.Add("Message", $"Link ({linkToDelete.Title}) has been removed successfully");
            }
            return RedirectToAction("ViewOwnLinks", new {username = TempData.Peek("Username") as string});
        }

        public IActionResult AddLinkView()
        {
            return View();
        }

        public IActionResult AddLinkToDb(string title, string description)
        {
            User? currentUser = _context.Users.Where(u => u.Pseudo.Equals(TempData.Peek("Username") as string)).FirstOrDefault();
            if (currentUser != null)
            {
                _context.Add<Link>(new Link { Title = title, Description = description, UserId = currentUser.UserId, PublicationDate = _today });
                _context.SaveChanges();
                TempData.Add("addLinkSuccess", $"Link ({title}) created by user {currentUser.Pseudo} has been added!");
            }
            else
            {
                TempData.Add("addLinkSuccess", $"Error while trying to create link ({title})... User not found!");
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult addComment(string comment, int _linkid) {
            User? currentUser = _context.Users.Where(u => u.Pseudo.Equals(TempData.Peek("Username") as string)).FirstOrDefault();
            if(currentUser != null)
            {
                _context.Add<Comment>(new Comment { Text = comment, UserId = currentUser.UserId, LinkId = _linkid, PublicationDate = _today });
                _context.SaveChanges();
            }

            return RedirectToAction("ViewLink", new { linkid = _linkid });
        }

        public IActionResult checkVote(string votetype, int idlink)
        {
            User? currentUser = _context.Users.Where(u => u.Pseudo.Equals(TempData.Peek("Username") as string)).FirstOrDefault();
            Vote? vote = _context.Votes.Where(v => v.UserId == currentUser.UserId && v.LinkId == idlink).FirstOrDefault();
            if (vote != null)
            {
                switch (vote.Value)
                {
                    case 1:
                        switch (votetype)
                        {
                            case "upvote":
                                vote.Value = 0;
                                _context.SaveChanges();
                                break;
                            case "downvote":
                                vote.Value = -1;
                                _context.SaveChanges();
                                break;
                        }
                        break;
                    case 0:
                        switch (votetype)
                        {
                            case "upvote":
                                vote.Value = 1;
                                _context.SaveChanges();
                                break;
                            case "downvote":
                                vote.Value = -1;
                                _context.SaveChanges();
                                break;
                        }
                        break;
                    case -1:
                        switch (votetype)
                        {
                            case "upvote":
                                vote.Value = 1;
                                _context.SaveChanges();
                                break;
                            case "downvote":
                                vote.Value = 0;
                                _context.SaveChanges();
                                break;
                        }
                        break;
                }
            }
            else
            {
                if (votetype.Equals("upvote"))
                {
                    _context.Add<Vote>(new Vote { LinkId = idlink, UserId = currentUser.UserId, Value = 1});
                    _context.SaveChanges();
                }
                else
                {
                    if (votetype.Equals("downvote"))
                    {
                        _context.Add<Vote>(new Vote { LinkId = idlink, UserId = currentUser.UserId, Value = -1 });
                        _context.SaveChanges();
                    }
                }
            }
            return RedirectToAction("ViewLink", new { linkid = idlink });
        }
    }
}

StopItEF/Views/Links/AddLinkView.cshtml
@{
    ViewData["Title"] = "Add link";
    Layout = "_Layout";
}

<!DOCTYPE html>
<html lang="en">
    <head>
    <link rel="stylesheet" href="~/css/AddLink.css" asp-append-version="true" />
    </head>
<body style="background-color: black">
    <div class="text-center">
        <h1 class="display-4" style="color:orangered;">Add a link</h1>
        <hr />
        <form action="addlinktodb" method="post" class="mainDiv">
            <input class="titleInput form-control" type="text" name="title" id="" placeholder="Enter title here..." maxlength="255" required />
            <br />
            <textarea name="description" id="" placeholder="Enter a description (Optional)" class="descInput form-control" maxlength="2000" rows="10"></textarea>
            <br />
            <input type="submit" value="Publish link" class="form-control" />
        </form>
    </div>
</body>
</html>

StopItEF/Views/Links/ViewLink.cshtml
@model StopItEF.Models.Link
@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
    int? amountOfVotes = 0;
    foreach (Vote vote in Model.Votes)
    {
        amountOfVotes += vote.Value;
    }
    int? upvotes = Model.Votes.Where(v => v.Value == 1).Count();
    int? downvotes = Model.Votes.Where(v => v.Value == -1).Count();
}
<!DOCTYPE html>

<html>
    <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/ViewLink.css" asp-append-version="true" />
    </head>
<body style="background-color: black;">

<div>
    <h1 class="display-4" style="color:orangered; text-align: center;">Link Details</h1>
    <hr />
    <div class="topG">
            <p class="description">@Model.Description</p>
            <div class="votes">
                <p><span style="color: black; font-weight: bold;">Rating: </span><span style="color: black; font-weight: bolder;">@amountOfVotes Vote(s)</span></p>
                <span class="upvote">@upvotes   <a asp-action="checkVote" asp-controller="Links" asp-route-votetype="upvote" asp-route-idlink="@Model.LinkId" style="text-decoration: none;"><i class="fa fa-thumbs-up" style="color: blue;"></i></a></span> <br />
                <span style="font-size: 30px;">@downvotes   <a asp-action="checkVote" asp-controller="Links" asp-route-votetype="downvote" asp-route-idlink="@Model.LinkId" style="text-decoration: none;"><i class="fa fa-thumbs-down" style="color: red;"></i></a></span>

            </div>
            <div class="centerInfo">
                <div class="titleDiv">
                    <p class="title">@Model.Title</p>
                </div>
                <p class="postedBy">Posted by @Model.User.Pseudo on @Model.PublicationDate</p>
            </div>
    </div>
</div>
<form action="addComment" method="post" class="mainDiv">
    <div style="align-content:center;">
            <textarea rows="3" cols="100" type="text" placeholder="What is your reaction to this link?" name="comment" maxlength="2000" required></textarea>
    </div>
        <br />
        <input type="text" value="@Model.LinkId" name="_linkid" hidden/>
        <div style="display: flex; flex-direction: column; align-items: flex-end;">
            <input type="submit" value="Comment" class="form-control" />
        </div>
        <br />
    </form>
<div>
    <h1 style="color: white;">Comments</h1>
    <hr />
    @foreach(var comment in Model.Comments){
        <partial name="_CommentTemplate" model="comment" />
    }
</div>
</body>
</html>

StopItEF/Views/Links/ViewOwnLinks.cshtml
@{
    ViewData["Title"] = "User Links";
    Layout = "_Layout";

}
@model IEnumerable<StopItEF.Models.Link>
<!DOCTYPE html>
<html lang="en">
    <head>
    <link rel="stylesheet" href="~/css/ViewOwnLinks.css" asp-append-version="true" />
    </head>
<body style="background-color: black">
    <div class="text-center">
        <h1 class="display-4" style="color:orangered;">Your links</h1>
        <hr />
        <div>
            @if(Model != null){
                @foreach (var item in Model)
                {
                    <partial name="_LinkTemplate" model="item" />
                    <div style="position:relative; margin-right: 130px; float: right; top: -160px;">
                        <a asp-action="DeleteLink" asp-controller="Links" asp-route-linkid="@item.LinkId" class="deleteLink">&#x274C; Delete</a>
                    </div>
                }
            }
            else{
                <p style="color:white;">No links found for this user!</p>
            }
        </div>
    </div>
    @if (ViewBag.Success != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Success");
            };
        </script>
    }
</body>
</html>